# Generated by Django 5.2.6 on 2026-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_store_mercadopago_access_token_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mp_payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
