# Generated by Django 5.2.6 on 2026-05-30 13:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Taxa de entrega cobrada nos pedidos online. 0,00 = entrega gratuita.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="free_delivery_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Pedidos com subtotal >= este valor ganham entrega gratuita. Nulo = recurso desativado.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Comanda Aberta"),
                    ("PENDING", "Pendente"),
                    ("PREPARING", "Preparando"),
                    ("DELIVERING", "Em trânsito"),
                    ("COMPLETED", "Concluído"),
                    ("CANCELED", "Cancelado"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
