# Generated by Django 5.2.6 on 2026-06-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_store_delivery_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="payment_card_enabled",
            field=models.BooleanField(
                default=True, help_text="Aceitar pagamento com cartão na maquininha."
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="payment_cash_enabled",
            field=models.BooleanField(
                default=True, help_text="Aceitar pagamento em dinheiro na entrega."
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="payment_online_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Aceitar pagamento online via MercadoPago (PIX/Checkout Pro).",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Comanda Aberta"),
                    ("PENDING", "Pendente"),
                    ("CONFIRMED", "Confirmado"),
                    ("PREPARING", "Preparando"),
                    ("DELIVERING", "Em trânsito"),
                    ("COMPLETED", "Concluído"),
                    ("CANCELED", "Cancelado"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
