from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name='catalog'),
    path('set-theme/', views.set_theme, name='set_theme'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
    path('cart/address/save/', views.save_address, name='save_address'),
    path('cart/address/delete/<int:address_id>/', views.delete_address, name='delete_address'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('save-location/', views.save_location, name='save_location'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/<int:order_id>/', views.payment_view, name='payment'),
    path('payment/success/', views.payment_success_view, name='payment_success'),
    path('payment/pending/', views.payment_pending_view, name='payment_pending'),
    path('payment/failure/', views.payment_failure_view, name='payment_failure'),
    path('payment/mock/', views.payment_mock_view, name='payment_mock'),
    path('payment/waiting/', views.payment_waiting_view, name='payment_waiting'),
    path('payment/waiting/status/', views.payment_waiting_status_view, name='payment_waiting_status'),
    # Manager Dashboard Area
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/toggle-delivery/', views.toggle_delivery_view, name='toggle_delivery'),
    path('dashboard/orders/', views.manager_orders, name='manager_orders'),
    path('dashboard/orders/rows/', views.manager_orders_rows, name='manager_orders_rows'),
    path('dashboard/order/<int:order_id>/update/', views.update_order_status, name='update_status'),
    path('dashboard/order/<int:order_id>/details/', views.order_details_modal, name='order_details'),
    path('dashboard/products/', views.manager_products, name='manager_products'),
    path('dashboard/products/create/', views.manager_product_create, name='manager_product_create'),
    path('dashboard/products/<int:product_id>/edit/', views.manager_product_edit, name='manager_product_edit'),
    path('dashboard/settings/', views.manager_settings, name='manager_settings'),
    path('account/', views.account_dashboard, name='account_dashboard'),
    path('account/addresses/', views.account_addresses, name='account_addresses'),
    path('account/orders/', views.account_orders, name='account_orders'),
    path('account/orders/<int:order_id>/', views.account_order_detail, name='account_order_detail'),
    path('dashboard/order/<int:order_id>/details/', views.order_details_modal, name='order_details'),
    path('dashboard/order/<int:order_id>/update/', views.update_order_status, name='update_status'),
    path('order/<int:order_id>/track/', views.order_track, name='order_track'),
    path('dashboard/order/<int:order_id>/print/', views.order_print, name='order_print'),
    path('dashboard/create/', views.manager_create_order, name='manager_create_order'),
    # Comandas
    path('dashboard/comandas/', views.comanda_list, name='comanda_list'),
    path('dashboard/comandas/create/', views.comanda_create, name='comanda_create'),
    path('dashboard/comandas/<int:comanda_id>/', views.comanda_detail, name='comanda_detail'),
    path('dashboard/comandas/<int:comanda_id>/add-item/', views.comanda_add_item, name='comanda_add_item'),
    path('dashboard/comandas/<int:comanda_id>/remove-item/<int:item_id>/', views.comanda_remove_item, name='comanda_remove_item'),
    path('dashboard/comandas/<int:comanda_id>/close/', views.comanda_close, name='comanda_close'),
]
